### ISSUE TITLE
Configure logging during installation

### ISSUE THREAD

**Issue by Systemmanic** [syncdk/homebrew-aws-session-manager-plugin#1]
Ensure logging is configured during installation.

As the path to the configuration is hardcoded in the plugin, this falls outside of the Homebrew installation. 

Need to investigate how this can function.

Requirements:

* Logging example configuration is installed to avoid manual file/directory creation.
* Logging configuration will work the same as outlined in the AWS documentation.
* Not enabled by default (as outlined in AWS documentation, it's optional)

**Comment by Systemmanic** [comment]
Nothing in the documentation on how to change this directory used by the plugin so logging config has to be created in the default directory: `/usr/local/sessionmanagerplugin`.

This is suffering from the same directory issues as #2 

Brew also can't symlink as it requires `sudo`

**Comment by tadlaht** [comment]
help

**Comment by Systemmanic** [comment]
@tadlaht ?

**Comment by Systemmanic** [comment]
No longer required, please see #11
