### ISSUE TITLE
Add Linux Support 

### ISSUE THREAD

**Issue by shreyasmm** [syncdk/homebrew-aws-session-manager-plugin#18]
The package installed very fine by running ```brew install aws-session-manager-plugin``` on ubuntu
But Permission issue 
```bash
ls -lah
.r--r--r-- shrey shrey 14.8 MB Mon Jan  6 19:27:58 2020 session-manager-plugin
```
It Complied for Mac
````bash
file session-manager-plugin 
session-manager-plugin: Mach-O 64-bit x86_64 executable
````
Can you please add support for linux

**Comment by Systemmanic** [comment]
It's supposed to make it executable: https://docs.brew.sh/Formula-Cookbook#bininstall-foo

I'll take a closer look 👍

**Comment by Systemmanic** [comment]
After some investigation: I can't add multi-arch support to this formula as it would need to be done in a cask with bottles, and this is staying as a Formula type.

The best way to get Linux support would be to request the change on the Cask in homebrew/homebrew-cask:

https://github.com/Homebrew/homebrew-cask/blob/master/Casks/session-manager-plugin.rb
